name = "flare-email-sender"
main = "src/index.ts"
compatibility_date = "2025-06-01"
account_id = "3adf03d991843094a7343eebc0a98007"

[vars]
WORKER_SCRIPT_NAME = "flare-email-sender"
INBOUND_BUCKET_NAME = "flare-email-inbound"

[[kv_namespaces]]
binding = "KEYS"
id = "341bf6e6f3c943a8a4f73128a98eb795"
preview_id = "fe42e6d5f04741f7a09516f25504581a"

[[r2_buckets]]
binding = "INBOUND"
bucket_name = "flare-email-inbound"
