import 'package:flutter/cupertino.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../../config/deep_links.dart';
import '../../providers/app_providers.dart';
import '../../providers/auth_provider.dart';
import '../../theme/colors.dart';
import '../../utils/validators.dart';

/// Pairing screen: sign in with account email + password. The Worker URL is
/// obtained by scanning the QR code generated by the desktop Other device
/// tab (it encodes workerUrl + email + password), or entered manually once.
/// The last-used email and Worker URL are remembered so the user only needs
/// the password on subsequent sign-ins.
class ConnectScreen extends ConsumerStatefulWidget {
  const ConnectScreen({super.key});

  @override
  ConsumerState<ConnectScreen> createState() => _ConnectScreenState();
}

class _ConnectScreenState extends ConsumerState<ConnectScreen> {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  final _workerUrlController = TextEditingController();
  bool _obscurePassword = true;
  bool _scanning = false;
  bool _showWorkerField = false;

  @override
  void initState() {
    super.initState();
    _prefill();
  }

  Future<void> _prefill() async {
    final storage = await ref.read(storageServiceProvider.future);
    final lastEmail = storage.lastEmail;
    final lastWorkerUrl = storage.lastWorkerUrl;
    if (!mounted) return;
    if (lastEmail != null && lastEmail.isNotEmpty) {
      _emailController.text = lastEmail;
    }
    if (lastWorkerUrl != null && lastWorkerUrl.isNotEmpty) {
      _workerUrlController.text = lastWorkerUrl;
    } else {
      // No stored Worker URL yet — show the field so the user can enter it
      // (or scan a QR which fills it automatically).
      setState(() => _showWorkerField = true);
    }
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    _workerUrlController.dispose();
    super.dispose();
  }

  Future<void> _connect() async {
    final email = _emailController.text.trim();
    final password = _passwordController.text.trim();
    final workerUrl = _workerUrlController.text.trim();
    if (email.isEmpty || password.isEmpty) return;
    if (!Validators.isEmail(email)) {
      _toast('Enter a valid account email address');
      return;
    }
    // Remember the email (and Worker URL if provided) immediately so they
    // pre-fill next time, even if this attempt fails.
    final storage = await ref.read(storageServiceProvider.future);
    await storage.rememberLastUsed(email: email, workerUrl: workerUrl);

    final ok = await ref.read(authProvider.notifier).connect(
          accountEmail: email,
          password: password,
          workerUrl: workerUrl.isEmpty ? null : workerUrl,
        );
    if (!ok && mounted) {
      final error = ref.read(authProvider).error ?? 'Could not connect';
      _toast(error);
    }
  }

  void _toast(String message) {
    showCupertinoDialog<void>(
      context: context,
      builder: (c) => CupertinoAlertDialog(
        title: const Text('Could not sign in'),
        content: Text(message),
        actions: [
          CupertinoDialogAction(
            isDefaultAction: true,
            onPressed: () => Navigator.of(c).pop(),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final auth = ref.watch(authProvider);
    final colors = ThemeColors.of(context);
    return CupertinoPageScaffold(
      backgroundColor: colors.surface,
      child: SafeArea(
        child: _scanning
            ? _ScannerView(
                onDone: (result) {
                  if (result != null) {
                    final parsed = ConnectDeepLink.parse(result);
                    if (parsed != null) {
                      _emailController.text = parsed.email;
                      _passwordController.text = parsed.password;
                      _workerUrlController.text = parsed.workerUrl;
                    } else {
                      _toast('Not a Relaybase pairing code');
                    }
                  }
                  setState(() => _scanning = false);
                },
              )
            : _form(context, auth, colors),
      ),
    );
  }

  Widget _form(BuildContext context, AuthState auth, ThemeColors colors) {
    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Icon(CupertinoIcons.envelope_open_fill, size: 64, color: colors.primary),
          const SizedBox(height: 16),
          Text(
            'Relaybase',
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 28, fontWeight: FontWeight.w700, color: colors.onSurface),
          ),
          const SizedBox(height: 6),
          Text(
            'Sign in with your account email and password.',
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 14, color: colors.onSurfaceVariant),
          ),
          const SizedBox(height: 32),
          _field(
            controller: _emailController,
            placeholder: 'Account email',
            keyboardType: TextInputType.emailAddress,
            autocorrect: false,
            prefixIcon: CupertinoIcons.person_crop_circle,
          ),
          const SizedBox(height: 12),
          _field(
            controller: _passwordController,
            placeholder: 'Password',
            obscureText: _obscurePassword,
            autocorrect: false,
            prefixIcon: CupertinoIcons.lock_fill,
            suffix: CupertinoButton(
              padding: EdgeInsets.zero,
              minSize: 0,
              onPressed: () => setState(() => _obscurePassword = !_obscurePassword),
              child: Icon(
                _obscurePassword ? CupertinoIcons.eye : CupertinoIcons.eye_slash,
                size: 20,
                color: colors.onSurfaceVariant,
              ),
            ),
          ),
          if (_showWorkerField) ...[
            const SizedBox(height: 12),
            _field(
              controller: _workerUrlController,
              placeholder: 'Worker URL (https://…)',
              keyboardType: TextInputType.url,
              autocorrect: false,
              prefixIcon: CupertinoIcons.globe,
            ),
          ],
          if (!_showWorkerField)
            Padding(
              padding: const EdgeInsets.only(top: 6),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  CupertinoButton(
                    padding: EdgeInsets.zero,
                    minSize: 0,
                    onPressed: () => setState(() => _showWorkerField = true),
                    child: Text(
                      'Change Worker',
                      style: TextStyle(fontSize: 12, color: colors.primary),
                    ),
                  ),
                ],
              ),
            ),
          const SizedBox(height: 24),
          CupertinoButton(
            color: colors.primary,
            borderRadius: BorderRadius.circular(12),
            padding: const EdgeInsets.symmetric(vertical: 14),
            onPressed: auth.loading ? null : _connect,
            child: auth.loading
                ? const CupertinoActivityIndicator(color: CupertinoColors.white)
                : Text(
                    'Sign in',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                      color: colors.onPrimary,
                    ),
                  ),
          ),
          const SizedBox(height: 12),
          CupertinoButton(
            padding: const EdgeInsets.symmetric(vertical: 10),
            onPressed: auth.loading ? null : () => setState(() => _scanning = true),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(CupertinoIcons.qrcode_viewfinder, size: 20, color: colors.primary),
                const SizedBox(width: 8),
                Text('Scan pairing QR', style: TextStyle(color: colors.primary, fontSize: 15)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _field({
    required TextEditingController controller,
    required String placeholder,
    required IconData prefixIcon,
    TextInputType? keyboardType,
    bool obscureText = false,
    bool autocorrect = true,
    Widget? suffix,
  }) {
    return CupertinoTextField(
      controller: controller,
      placeholder: placeholder,
      keyboardType: keyboardType,
      obscureText: obscureText,
      autocorrect: autocorrect,
      prefix: Padding(
        padding: const EdgeInsets.only(left: 12),
        child: Icon(prefixIcon, size: 20, color: ThemeColors.of(context).onSurfaceVariant),
      ),
      suffix: suffix == null ? null : Padding(padding: const EdgeInsets.only(right: 12), child: suffix),
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
      decoration: BoxDecoration(
        color: ThemeColors.of(context).surfaceVariant,
        borderRadius: BorderRadius.circular(12),
      ),
    );
  }
}

class _ScannerView extends StatefulWidget {
  const _ScannerView({required this.onDone});
  final ValueChanged<String?> onDone;

  @override
  State<_ScannerView> createState() => _ScannerViewState();
}

class _ScannerViewState extends State<_ScannerView> {
  late final MobileScannerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = MobileScannerController(
      detectionSpeed: DetectionSpeed.noDuplicates,
      formats: const [BarcodeFormat.qrCode],
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        MobileScanner(
          controller: _controller,
          onDetect: (capture) {
            final barcodes = capture.barcodes;
            if (barcodes.isEmpty) return;
            final raw = barcodes.first.rawValue;
            _controller.stop();
            widget.onDone(raw);
          },
        ),
        Positioned(
          top: 8,
          left: 8,
          child: CupertinoButton(
            color: const Color(0x88000000),
            padding: const EdgeInsets.all(8),
            onPressed: () => widget.onDone(null),
            child: const Icon(CupertinoIcons.xmark, color: CupertinoColors.white),
          ),
        ),
      ],
    );
  }
}
