/** Static PNG thumbnails generated by `pnpm run generate:message-template-thumbnails`. */
export const MESSAGE_TEMPLATE_THUMBNAILS_PUBLIC_DIR = "/studio/message-template-thumbnails";

export function messageTemplateThumbnailPublicPath(templateId: string): string {
  return `${MESSAGE_TEMPLATE_THUMBNAILS_PUBLIC_DIR}/${templateId}.png`;
}

/** Shipped presets / CI-generated assets — custom templates capture client-side. */
export function resolveMessageTemplateThumbnailPublicPath(input: {
  templateId: string;
  isPreset: boolean;
}): string | null {
  if (!input.isPreset) return null;
  return messageTemplateThumbnailPublicPath(input.templateId);
}
