/** Static PNG thumbnails generated by `pnpm run generate:layout-thumbnails`. */
export const LAYOUT_THUMBNAILS_PUBLIC_DIR = "/studio/layout-thumbnails";

export function layoutThumbnailPublicPath(layoutId: string): string {
  return `${LAYOUT_THUMBNAILS_PUBLIC_DIR}/${layoutId}.png`;
}

/** Built-in layouts only — custom imports fall back to wireframe in the UI. */
export function resolveLayoutThumbnailPublicPath(input: {
  layoutId: string;
  isBuiltin: boolean;
}): string | null {
  if (!input.isBuiltin) return null;
  return layoutThumbnailPublicPath(input.layoutId);
}
