import { defineConfig } from "drizzle-kit";

/**
 * drizzle-kit config for the `relaybase-db` (binding `RELAYBASE_DB`) migrations.
 *
 * `migrations-logs/` and `migrations-inbox/` already exist as hand-written
 * wrangler SQL — they are NOT regenerated by drizzle-kit. This config only
 * generates `migrations-app/` from `db/app/schema.ts`.
 *
 * Usage:
 *   pnpm exec drizzle-kit generate --config=drizzle.app.config.ts
 *   wrangler d1 migrations apply relaybase-db --remote
 */
export default defineConfig({
  schema: "./db/app/schema.ts",
  out: "./migrations-app",
  dialect: "sqlite",
  driver: "d1-http",
  dbCredentials: {
    accountId: process.env.CLOUDFLARE_ACCOUNT_ID!,
    databaseId: process.env.RELAYBASE_DB_ID!,
    token: process.env.CLOUDFLARE_API_TOKEN!,
  },
});
